config/routes.rb
Rails.application.routes.draw do
  resources :comments
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "comments#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  def verify_turnstile
    verified = Turnstile.verify(token: params["cf-turnstile-response"], ip: request.remote_ip)
    flash[:alert] = "Challenge failed, please try again." unless verified
    verified
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if verify_turnstile && @comment.save
        format.html { redirect_to @comment, notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy!

    respond_to do |format|
      format.html { redirect_to comments_path, status: :see_other, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.expect(comment: [ :body ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Body:</strong>
    <%= comment.body %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.textarea :body %>
  </div>

  <%= tag.div data: {controller: :turnstile, turnstile_site_key_value: ENV["TURNSTILE_SITE_KEY"]} %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<% content_for :title, "Editing comment" %>

<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Comments" %>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<% content_for :title, "New comment" %>

<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Turnstile Comments" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/views/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit"></script>
  </head>

  <body>
    <p style="color: red"><%= alert %></p>
    <%= yield %>
  </body>
</html>